const steps=[['1','Choose','Pick an API that interests you.'],['2','Test JSON','Run it and inspect the fields.'],['3','Copy model','Add the Codable model.'],['4','Add state','Add the @State variable(s).'],['5','Add screen','Replace the starter body with the complete SwiftUI body.'],['6','Add function','Add the API function.'],['7','Run + improve','Run the app, then make one design or feature improvement.'],['8','Evidence','Capture screenshots, testing and reflection.']];
document.querySelector('#steps').innerHTML=steps.map(s=>`<div class="step"><b>${s[0]}</b><strong>${s[1]}</strong><span>${s[2]}</span></div>`).join('');

const apis=[
{
id:'catfacts',name:'Cat Facts',subject:'Animals',level:'Easy',endpoint:'https://catfact.ninja/fact',fields:'Find “fact”. That is the text the app displays.',
model:`struct CatFact: Codable {\n    let fact: String\n}`,
fetch:`@State private var fact = "Loading…"\n\nfunc loadData() async {\n    guard let url = URL(string: "https://catfact.ninja/fact") else { return }\n    do {\n        let (data, _) = try await URLSession.shared.data(from: url)\n        let result = try JSONDecoder().decode(CatFact.self, from: data)\n        fact = result.fact\n    } catch {\n        fact = "Could not load a cat fact."\n    }\n}`,
view:`VStack(spacing: 20) {\n    Text("Cat Fact").font(.largeTitle.bold())\n    Text(fact)\n    Button("New Fact") { Task { await loadData() } }\n        .buttonStyle(.borderedProminent)\n}\n.padding()\n.task { await loadData() }`,
challenges:['Change the colours and fonts.','Add a counter for facts viewed.','Add a favourite fact button.']
},
{
id:'dogceo',name:'Dog CEO',subject:'Animals + Images',level:'Easy',endpoint:'https://dog.ceo/api/breeds/image/random',fields:'The dog image URL is in “message”.',
model:`struct DogResponse: Codable {\n    let message: String\n}`,
fetch:`@State private var imageURL = ""\n@State private var message = "Loading dog…"\n\nfunc loadData() async {\n    guard let url = URL(string: "https://dog.ceo/api/breeds/image/random") else { return }\n    do {\n        let (data, _) = try await URLSession.shared.data(from: url)\n        let result = try JSONDecoder().decode(DogResponse.self, from: data)\n        imageURL = result.message\n        message = "Tap for another dog"\n    } catch {\n        message = "Could not load a dog image."\n    }\n}`,
view:`VStack(spacing: 16) {\n    Text("Random Dog").font(.largeTitle.bold())\n    AsyncImage(url: URL(string: imageURL)) { phase in\n        if let image = phase.image {\n            image.resizable().scaledToFit()\n        } else if phase.error != nil {\n            Text("Image could not load")\n        } else {\n            ProgressView()\n        }\n    }\n    .frame(maxHeight: 350)\n    Text(message)\n    Button("Another Dog") { Task { await loadData() } }\n        .buttonStyle(.borderedProminent)\n}\n.padding()\n.task { await loadData() }`,
challenges:['Add a dog counter.','Change the layout.','Add a favourites idea.']
},
{
id:'fishwatch',name:'FishWatch',subject:'Science + Environment',level:'Easy',endpoint:'https://www.fishwatch.gov/api/species',fields:'Each item contains “Species Name” and “Scientific Name”.',
model:`struct Fish: Codable {\n    let speciesName: String?\n    let scientificName: String?\n\n    enum CodingKeys: String, CodingKey {\n        case speciesName = "Species Name"\n        case scientificName = "Scientific Name"\n    }\n}`,
fetch:`@State private var fish: [Fish] = []\n@State private var message = "Loading fish…"\n\nfunc loadData() async {\n    guard let url = URL(string: "https://www.fishwatch.gov/api/species") else { return }\n    do {\n        let (data, _) = try await URLSession.shared.data(from: url)\n        fish = try JSONDecoder().decode([Fish].self, from: data)\n        message = "Loaded \\(fish.count) species"\n    } catch {\n        message = "Could not load FishWatch data."\n    }\n}`,
view:`VStack {\n    Text(message).font(.headline)\n    List(fish.prefix(20), id: \\.speciesName) { item in\n        VStack(alignment: .leading) {\n            Text(item.speciesName ?? "Unknown fish").font(.headline)\n            Text(item.scientificName ?? "").font(.caption)\n        }\n    }\n}\n.task { await loadData() }`,
challenges:['Add search.','Show only 10 species.','Add a fish detail page.']
},
{
id:'art',name:'Art Institute of Chicago',subject:'Art + Images',level:'Easy',endpoint:'https://api.artic.edu/api/v1/artworks/27992?fields=id,title,artist_display,image_id',fields:'Inside “data”, find title, artist_display and image_id.',
model:`struct ArtResponse: Codable {\n    let data: Artwork\n}\n\nstruct Artwork: Codable {\n    let title: String\n    let artist_display: String?\n    let image_id: String?\n}`,
fetch:`@State private var artwork: Artwork?\n@State private var message = "Loading artwork…"\n\nfunc loadData() async {\n    let address = "https://api.artic.edu/api/v1/artworks/27992?fields=id,title,artist_display,image_id"\n    guard let url = URL(string: address) else { return }\n    do {\n        let (data, _) = try await URLSession.shared.data(from: url)\n        artwork = try JSONDecoder().decode(ArtResponse.self, from: data).data\n        message = ""\n    } catch {\n        message = "Could not load artwork."\n    }\n}`,
view:`VStack(spacing: 12) {\n    if let art = artwork {\n        if let imageID = art.image_id {\n            let imageURL = URL(string: "https://www.artic.edu/iiif/2/\\(imageID)/full/400,/0/default.jpg")\n            AsyncImage(url: imageURL) { image in\n                image.resizable().scaledToFit()\n            } placeholder: {\n                ProgressView()\n            }\n            .frame(maxHeight: 350)\n        }\n        Text(art.title).font(.title.bold())\n        Text(art.artist_display ?? "Unknown artist")\n    } else {\n        Text(message)\n        ProgressView()\n    }\n}\n.padding()\n.task { await loadData() }`,
challenges:['Change the artwork ID.','Add a border around the image.','Create a museum information card.']
},
{
id:'emojihub',name:'EmojiHub',subject:'Emoji + Design',level:'Easy',endpoint:'https://emojihub.yurace.pro/api/random',fields:'Find “name”, “category” and “unicode”.',
model:`struct EmojiItem: Codable {\n    let name: String\n    let category: String\n    let unicode: [String]\n}`,
fetch:`@State private var emoji: EmojiItem?\n@State private var message = "Loading emoji…"\n\nfunc loadData() async {\n    guard let url = URL(string: "https://emojihub.yurace.pro/api/random") else { return }\n    do {\n        let (data, _) = try await URLSession.shared.data(from: url)\n        emoji = try JSONDecoder().decode(EmojiItem.self, from: data)\n        message = ""\n    } catch {\n        message = "Could not load an emoji."\n    }\n}`,
view:`VStack(spacing: 16) {\n    Text("Emoji Explorer").font(.largeTitle.bold())\n    Text(emoji?.name ?? message).font(.title2)\n    Text(emoji?.category ?? "")\n    Text(emoji?.unicode.first ?? "")\n    Button("Another Emoji") { Task { await loadData() } }\n        .buttonStyle(.borderedProminent)\n}\n.padding()\n.task { await loadData() }`,
challenges:['Make an emoji guessing game.','Change colours based on category.','Add a score counter.']
},
{
id:'amiibo',name:'AmiiboAPI',subject:'Games + Images',level:'Easy',endpoint:'https://amiiboapi.org/api/amiibo/?name=mario',fields:'Inside “amiibo”, find name, character and image.',
model:`struct AmiiboResponse: Codable {\n    let amiibo: [Amiibo]\n}\n\nstruct Amiibo: Codable {\n    let name: String\n    let character: String\n    let image: String\n}`,
fetch:`@State private var item: Amiibo?\n@State private var message = "Loading Mario…"\n\nfunc loadData() async {\n    guard let url = URL(string: "https://amiiboapi.org/api/amiibo/?name=mario") else { return }\n    do {\n        let (data, _) = try await URLSession.shared.data(from: url)\n        let result = try JSONDecoder().decode(AmiiboResponse.self, from: data)\n        item = result.amiibo.first\n        message = item == nil ? "No Amiibo found." : ""\n    } catch {\n        message = "Could not load Amiibo data."\n    }\n}`,
view:`VStack(spacing: 14) {\n    if let item = item {\n        AsyncImage(url: URL(string: item.image)) { image in\n            image.resizable().scaledToFit()\n        } placeholder: {\n            ProgressView()\n        }\n        .frame(maxHeight: 320)\n        Text(item.name).font(.title.bold())\n        Text(item.character)\n    } else {\n        Text(message)\n        ProgressView()\n    }\n}\n.padding()\n.task { await loadData() }`,
challenges:['Search for Zelda instead.','Add a coloured background.','Create a character collection page.']
},
{
id:'rickmorty',name:'Rick and Morty API',subject:'Characters + Images',level:'Easy',endpoint:'https://rickandmortyapi.com/api/character/1',fields:'Find name, status, species and image.',
model:`struct Character: Codable {\n    let name: String\n    let status: String\n    let species: String\n    let image: String\n}`,
fetch:`@State private var character: Character?\n@State private var message = "Loading character…"\n\nfunc loadData() async {\n    guard let url = URL(string: "https://rickandmortyapi.com/api/character/1") else { return }\n    do {\n        let (data, _) = try await URLSession.shared.data(from: url)\n        character = try JSONDecoder().decode(Character.self, from: data)\n        message = ""\n    } catch {\n        message = "Could not load the character."\n    }\n}`,
view:`VStack(spacing: 12) {\n    if let character = character {\n        AsyncImage(url: URL(string: character.image)) { phase in\n            if let image = phase.image {\n                image.resizable().scaledToFit()\n            } else if phase.error != nil {\n                Text("Image unavailable")\n            } else {\n                ProgressView()\n            }\n        }\n        .frame(maxHeight: 320)\n        Text(character.name).font(.title.bold())\n        Text("Status: \\(character.status)")\n        Text("Species: \\(character.species)")\n    } else {\n        Text(message)\n        ProgressView()\n    }\n}\n.padding()\n.task { await loadData() }`,
challenges:['Change character 1 to another ID.','Colour-code Alive/Dead status.','Add a next character button.']
},
{
id:'openmeteo',name:'Open-Meteo',subject:'Weather + Data',level:'Easy',endpoint:'https://api.open-meteo.com/v1/forecast?latitude=-28.0167&longitude=153.4&current=temperature_2m,wind_speed_10m',fields:'Inside “current”, find temperature_2m and wind_speed_10m.',
model:`struct WeatherResponse: Codable {\n    let current: CurrentWeather\n}\n\nstruct CurrentWeather: Codable {\n    let temperature_2m: Double\n    let wind_speed_10m: Double\n}`,
fetch:`@State private var weather: WeatherResponse?\n@State private var message = "Loading weather…"\n\nfunc loadData() async {\n    let address = "https://api.open-meteo.com/v1/forecast?latitude=-28.0167&longitude=153.4&current=temperature_2m,wind_speed_10m"\n    guard let url = URL(string: address) else { return }\n    do {\n        let (data, _) = try await URLSession.shared.data(from: url)\n        weather = try JSONDecoder().decode(WeatherResponse.self, from: data)\n        message = ""\n    } catch {\n        message = "Could not load weather."\n    }\n}`,
view:`VStack(spacing: 18) {\n    Text("Gold Coast Weather").font(.largeTitle.bold())\n    if let weather = weather {\n        Text("Temperature: \\(weather.current.temperature_2m) °C").font(.title)\n        Text("Wind: \\(weather.current.wind_speed_10m) km/h").font(.title2)\n    } else {\n        Text(message)\n        ProgressView()\n    }\n    Button("Refresh") { Task { await loadData() } }\n        .buttonStyle(.borderedProminent)\n}\n.padding()\n.task { await loadData() }`,
challenges:['Change the latitude and longitude.','Add an SF Symbol weather icon.','Compare two locations.']
},
{
id:'spaceflight',name:'Spaceflight News',subject:'Space + News',level:'Easy',endpoint:'https://api.spaceflightnewsapi.net/v4/articles/?limit=5',fields:'Inside “results”, find title. The example deliberately uses only the title to keep decoding simple.',
model:`struct NewsResponse: Codable {\n    let results: [Article]\n}\n\nstruct Article: Codable, Identifiable {\n    let id: Int\n    let title: String\n}`,
fetch:`@State private var news: [Article] = []\n@State private var message = "Loading space news…"\n\nfunc loadData() async {\n    guard let url = URL(string: "https://api.spaceflightnewsapi.net/v4/articles/?limit=5") else { return }\n    do {\n        let (data, _) = try await URLSession.shared.data(from: url)\n        news = try JSONDecoder().decode(NewsResponse.self, from: data).results\n        message = ""\n    } catch {\n        message = "Could not load space news."\n    }\n}`,
view:`VStack {\n    Text("Latest Space News").font(.largeTitle.bold()).padding()\n    if news.isEmpty {\n        Text(message)\n        ProgressView()\n    } else {\n        List(news) { article in\n            Text(article.title).font(.headline)\n        }\n    }\n}\n.task { await loadData() }`,
challenges:['Add article summaries later.','Add a space icon.','Create a favourite headline feature.']
},
{
id:'holidays',name:'Nager.Date Holidays',subject:'Calendar + Countries',level:'Easy',endpoint:'https://date.nager.at/api/v3/PublicHolidays/2026/AU',fields:'Each holiday has date and localName.',
model:`struct Holiday: Codable, Identifiable {\n    var id: String { date + localName }\n    let date: String\n    let localName: String\n}`,
fetch:`@State private var holidays: [Holiday] = []\n@State private var message = "Loading holidays…"\n\nfunc loadData() async {\n    guard let url = URL(string: "https://date.nager.at/api/v3/PublicHolidays/2026/AU") else { return }\n    do {\n        let (data, _) = try await URLSession.shared.data(from: url)\n        holidays = try JSONDecoder().decode([Holiday].self, from: data)\n        message = ""\n    } catch {\n        message = "Could not load holidays."\n    }\n}`,
view:`VStack {\n    Text("Australian Holidays").font(.largeTitle.bold()).padding()\n    if holidays.isEmpty {\n        Text(message)\n        ProgressView()\n    } else {\n        List(holidays) { holiday in\n            VStack(alignment: .leading) {\n                Text(holiday.localName).font(.headline)\n                Text(holiday.date).font(.caption)\n            }\n        }\n    }\n}\n.task { await loadData() }`,
challenges:['Show only the next five holidays.','Change AU to another country code.','Add a countdown idea.']
}
];

let current=apis[0];
const apiList=document.querySelector('#apiList'),detail=document.querySelector('#detail'),search=document.querySelector('#search'),promptApi=document.querySelector('#promptApi');
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
function renderList(filter=''){const list=apis.filter(a=>(a.name+' '+a.subject).toLowerCase().includes(filter.toLowerCase()));apiList.innerHTML=list.map(a=>`<button class="api-btn ${a.id===current.id?'active':''}" data-id="${a.id}"><strong>${a.name}</strong><span>${a.subject} · ${a.level}</span></button>`).join('');apiList.querySelectorAll('button').forEach(b=>b.onclick=()=>{current=apis.find(a=>a.id===b.dataset.id);renderList(search.value);renderDetail();promptApi.value=current.id})}
function code(title,n,text,id,help){return `<div class="block"><div class="num">Step ${n}</div><h3>${title}</h3><p class="muted">${help}</p><div class="actions"><button data-copy="${id}">Copy this Swift code</button><span id="s-${id}"></span></div><pre id="${id}">${esc(text)}</pre></div>`}
function renderDetail(){detail.innerHTML=`<p class="eyebrow">${current.subject}</p><h2>${current.name}</h2><span class="tag">No API key</span><span class="tag">Auto-loads</span><span class="tag">iPad ready</span><div class="block"><div class="num">Step 2</div><h3>Test the API</h3><p class="muted">Inspect the JSON before writing Swift.</p><div class="endpoint">${current.endpoint}</div><div class="actions"><button id="testApi" class="primary">Test API</button><span id="testStatus"></span></div><pre id="liveOutput">Live response will appear here.</pre><div class="question"><strong>JSON detective:</strong> ${current.fields}</div></div>${code('Create the Codable model',3,current.model,'model','Only decode the fields this beginner app actually needs.')}${code('State + API routine',4,current.fetch,'fetch','This includes a visible loading/error message so a failed request does not look like a blank screen.')}${code('Build the SwiftUI screen',5,current.view,'view','This screen calls loadData automatically using .task, so data should appear without an extra first tap.')}<div class="block"><div class="num">Step 7</div><h3>Make it yours</h3><div class="challenges">${current.challenges.map((c,i)=>`<div class="challenge"><strong>Challenge ${i+1}</strong><br>${c}</div>`).join('')}</div></div>`;document.querySelector('#testApi').onclick=testApi;detail.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>copy(document.querySelector('#'+b.dataset.copy).textContent,'s-'+b.dataset.copy))}
async function copy(text,status){try{await navigator.clipboard.writeText(text);document.querySelector('#'+status).textContent='Copied — paste into Swift Playgrounds.'}catch{document.querySelector('#'+status).textContent='Copy failed — select the code manually.'}}
async function testApi(){const out=document.querySelector('#liveOutput'),status=document.querySelector('#testStatus');out.textContent='Loading…';status.textContent='Requesting data…';try{const r=await fetch('/api/live?id='+current.id),d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');out.textContent=JSON.stringify(Array.isArray(d)?d.slice(0,3):d,null,2).slice(0,7000);status.textContent='Success — now identify the fields you need.'}catch(e){out.textContent=e.message;status.textContent='Try again or choose another API.'}}
search.oninput=e=>renderList(e.target.value);promptApi.innerHTML=apis.map(a=>`<option value="${a.id}">${a.name}</option>`).join('');
document.querySelector('#makePrompt').onclick=()=>{const api=apis.find(a=>a.id===promptApi.value),goal=document.querySelector('#promptGoal').value,idea=document.querySelector('#promptIdea').value;const goals={feature:'suggest three realistic new features and help me choose one',interface:'help me improve the SwiftUI interface',debug:'help me diagnose a Codable, URLSession, JSON or SwiftUI error',data:'show me how to use one or two more useful JSON fields',accessibility:'help me improve readability, VoiceOver, labels, spacing and contrast'};document.querySelector('#promptOutput').textContent=`I am a Year 7 or 8 student using Swift Playgrounds on an iPad. I am using the ${api.name} API (${api.endpoint}) to build ${idea}.\n\nPlease ${goals[goal]}.\n\nExplain each change simply. Do not rebuild the whole app. Keep the code suitable for Swift Playgrounds and use async/await with URLSession.`;document.querySelector('#copyPrompt').disabled=false};
document.querySelector('#copyPrompt').onclick=()=>navigator.clipboard.writeText(document.querySelector('#promptOutput').textContent);
const evidenceItems=['API chosen and tested','JSON fields identified','Working SwiftUI app screenshot','Code screenshot','One improvement added','One problem + how I fixed it','Short reflection'];
const evidence=document.querySelector('#evidence');evidence.innerHTML=evidenceItems.map((x,i)=>`<label><input type="checkbox" data-i="${i}"> ${x}</label>`).join('');
const saved=JSON.parse(localStorage.getItem('apiEvidence')||'[]');evidence.querySelectorAll('input').forEach((box,i)=>{box.checked=!!saved[i];box.onchange=()=>{const vals=[...evidence.querySelectorAll('input')].map(x=>x.checked);localStorage.setItem('apiEvidence',JSON.stringify(vals))}});
document.querySelector('#resetEvidence').onclick=()=>{localStorage.removeItem('apiEvidence');evidence.querySelectorAll('input').forEach(x=>x.checked=false)};
renderList();renderDetail();promptApi.value=current.id;
